development:
  clients:
    default:
      database: banking_system
      hosts:
        - 127.0.0.1:27017
      options:
        min_pool_size: <%= ENV['MONGO_POOL_SIZE'] || 16 %>
        max_pool_size: <%= ENV['MONGO_POOL_SIZE'] || 16 %>
        write:
          w: 1
        read:
          mode: :primary

  options:
    preload_models: true
    use_activesupport_time_zone: true
    belongs_to_required_by_default: false
